POST http://localhost:8080/create_account HTTP/1.1
Content-Type: application/json

{
    "username": "bob@jones.com",
    "password": "P@ssw0rd!"
}

###

POST http://localhost:8080/create_account HTTP/1.1
Content-Type: application/json

{
    "username": "bob1@jones.com",
    "password": "P@ssw0rd1!"
}

###

POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "bob@jones.com",
    "password": "P@ssw0rd!"
}

###

POST http://localhost:8080/create_account HTTP/1.1
Content-Type: application/json

{
    "username": "sally@jones.com",
    "password": "P@ssw0rd!"
}

###

POST http://localhost:8080/create_account HTTP/1.1
Content-Type: application/json

{
    "username": "john@smith.com",
    "password": "P@ssw0rd!"
}

###

POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "sally@jones.com",
    "password": "P@ssw0rd!"
}

###

POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "john@smith.com",
    "password": "P@ssw0rd!"
}

###

POST http://localhost:8080/refresh_token HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJtaWRlbyIsInN1YiI6ImJvYkBqb25lcy5jb20iLCJpZCI6IjY0N2EzNjZhNzBjM2M0NzRjMjVhZTVhNCIsImF1dGhvcml0aWVzIjoiVVNFUiIsImV4cCI6MTY4NjA4MjU0M30.eQpEIO_wgUsg7j-MV6jPu1tf5dawezVVgeUhaRVp9Yk

###
POST http://localhost:8080/watchable HTTP/1.1
Content-Type: application/json

{
    "type": "movie",
    "title": "Dogma",
    "overview": "Description",
    "imdbRating": 7,
    "personalRating": 8,
    "year": 2000
}

###

POST http://localhost:8080/watchable HTTP/1.1
Content-Type: application/json

{
    "type": "movie",
    "title": "Another Spiderman Movie",
    "overview": "Description",
    "imdbRating": 7,
    "personalRating": 8,
    "year": 2000,
    "imdbId": "ab12345"
}

###

POST http://localhost:8080/watchlist/647f56975d9aa5d43d05ddc6/addWatchable HTTP/1.1
Content-Type: application/json

{
    "type": "movie",
    "title": "Guardians of the Galaxy Vol. 3",
    "overview": "Peter Quill, still reeling from the loss of Gamora, must rally his team around him to defend the universe along with protecting one of their own. A mission that, if not completed successfully, could quite possibly lead to the end of the Guardians as we know them.",
    "year": 2023,
    "imdbRating": 83,
    "genres": [
        "Action",
        "Adventure"
    ],
    "posterPath": "/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg",
    "cast_members": [
        "Chris Pratt",
        "Zoe Saldaña",
        "Dave Bautista",
        "Karen Gillan",
        "Pom Klementieff",
        "Vin Diesel",
        "Bradley Cooper"
    ],
    "streamingServices": [
    ],
    "trailerLink": "https://www.youtube.com/watch?v=AAE5VZktooM",
    "id": "tt6791350",
    "personalRating": 92
}

###

POST http://localhost:8080/watchlist/647f56975d9aa5d43d05ddc7/addWatchable HTTP/1.1
Content-Type: application/json

{
        "type": "series",
        "title": "Ted Lasso",
        "overview": "Ted Lasso, an American football coach, moves to England when he’s hired to manage a soccer team—despite having no experience. With cynical players and a doubtful town, will he get them to see the Ted Lasso Way?",
        "firstAirYear": 2020,
        "lastAirYear": 2023,
        "imdbRating": 88,
        "genres": [
            "Comedy",
            "Drama",
            "Sport"
        ],
        "posterPath": "/5fhZdwP1DVJ0FyVH6vrFdHwpXIn.jpg",
        "cast_members": [
            "Jason Sudeikis",
            "Hannah Waddingham",
            "Jeremy Swift",
            "Phil Dunster",
            "Brett Goldstein",
            "Brendan Hunt",
            "Nick Mohammed"
        ],
        "id": "tt10986410",
        "personalRating": 88,
        "streamingServices": [
            "apple"
        ],
        "trailerLink": "https://www.youtube.com/watch?v=3u7EIiohs6U"
    }

###

POST http://localhost:8080/watchlist/647f56975d9aa5d43d05ddc8/addWatchable HTTP/1.1
Content-Type: application/json

{
    "type": "series",
    "title": "Breaking Bad",
    "overview": "When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
    "firstAirYear": 2008,
    "lastAirYear": 2013,
    "imdbRating": 95,
    "genres": [
        "Crime",
        "Drama",
        "Thriller"
    ],
    "posterPath": "/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
    "cast_members": [
        "Bryan Cranston",
        "Aaron Paul",
        "Anna Gunn",
        "Dean Norris",
        "Betsy Brandt",
        "RJ Mitte",
        "Bob Odenkirk"
    ],
    "id": "tt0903747",
    "personalRating": 100,
    "streamingServices": [
        "netflix"
    ],
    "trailerLink": "https://www.youtube.com/watch?v=XZ8daibM3AE"
    }

###

POST http://localhost:8080/watchlist/647f56975d9aa5d43d05ddc8/addWatchable HTTP/1.1
Content-Type: application/json

{
    "type": "movie",
    "title": "Pitch Perfect",
    "overview": "College student Beca knows she does not want to be part of a clique, but that's exactly where she finds herself after arriving at her new school. Thrust in among mean gals, nice gals and just plain weird gals, Beca finds that the only thing they have in common is how well they sing together. She takes the women of the group out of their comfort zone of traditional arrangements and into a world of amazing harmonic combinations in a fight to the top of college music competitions.",
    "year": 2012,
    "imdbRating": 71,
    "genres": [
        "Comedy",
        "Music",
        "Romance"
    ],
    "posterPath": "/ntRIoh8Qf1BI1AYGx0STfq0wUmb.jpg",
    "cast_members": [
        "Anna Kendrick",
        "Brittany Snow",
        "Anna Camp",
        "Rebel Wilson",
        "Skylar Astin",
        "Ester Dean",
        "Hana Mae Lee"
    ],
    "id": "tt1981677",
    "personalRating": 85,
    "streamingServices": [
        "apple",
        "netflix",
        "prime"
    ],
    "trailerLink": "https://www.youtube.com/watch?v=8dItOM6eYXY"
    }

###

DELETE http://localhost:8080/watchlist/647f56975d9aa5d43d05ddc6/removeWatchable/647f7e765d9aa5d43d05ddcd HTTP/1.1

###

GET http://localhost:8080/watchable/watchableById/647f7e765d9aa5d43d05ddcc HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8080/watchlist/647f56975d9aa5d43d05ddc6/addWatchable/647f7e765d9aa5d43d05ddcd HTTP/1.1
Content-Type: application/json

###

DELETE http://localhost:8080/watchable/647f7e765d9aa5d43d05ddce HTTP/1.1

###

GET http://localhost:8080/watchlist/byUserId/647e28cce9b45529f92d8dff HTTP/1.1

###

GET http://localhost:8080/watchable/watchableById/647f4b85d7919741dad6f8df HTTP/1.1
Content-Type: application/json

###

PUT http://localhost:8080/watchable/updatePersonalRating/647f4b85d7919741dad6f8df HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJtaWRlbyIsInN1YiI6ImJvYkBqb25lcy5jb20iLCJpZCI6IjY0N2EzNjZhNzBjM2M0NzRjMjVhZTVhNCIsImF1dGhvcml0aWVzIjoiVVNFUiIsImV4cCI6MTY4NjA4MjU0M30.eQpEIO_wgUsg7j-MV6jPu1tf5dawezVVgeUhaRVp9Yk

{
    "id": "647f4b85d7919741dad6f8df",
    "type": "movie",
    "title": "Dogma",
    "overview": "Description",
    "imdbRating": 7,
    "personalRating": 9,
    "trailerLink": null,
    "posterPath": null,
    "year": 2000,
    "firstAirYear": 0,
    "lastAirYear": 0,
    "genres": null,
    "streamingServices": null,
    "cast_members": null
}

###

POST http://localhost:8080/watchlist/647f56975d9aa5d43d05ddc8/addWatchable/648140706998250652bd7780 HTTP/1.1
Content-Type: application/json

###

DELETE http://localhost:8080/watchlist/647f56975d9aa5d43d05ddc8/removeWatchable/647fdebe2c841116eea0e320 HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8080/watchable HTTP/1.1
Content-Type: application/json

{
  "id": "6480b34dddaafa5a826a01e0",
  "type": "movie",
  "title": "Moana",
  "overview": "In Ancient Polynesia, when a terrible curse incurred by Maui reaches an impetuous Chieftain's daughter's island, she answers the Ocean's call to seek out the demigod to set things right.",
  "imdbRating": 76,
  "personalRating": 5,
  "trailerLink": "https://www.youtube.com/watch?v=LKFuXETZUsI",
  "posterPath": "/4JeejGugONWpJkbnvL12hVoYEDa.jpg",
  "year": 2016,
  "firstAirYear": 0,
  "lastAirYear": 0,
  "genres": [
    "Animation",
    "Adventure",
    "Comedy"
  ],
  "streamingServices": [
    "apple",
    "disney",
    "prime"
  ],
  "cast_members": [
    "Auli'i Cravalho",
    "Dwayne Johnson",
    "Rachel House",
    "Temuera Morrison",
    "Jemaine Clement",
    "Nicole Scherzinger",
    "Alan Tudyk"
  ],
  "_class": "learn.mideo.model.Watchable"
}

###

POST http://localhost:8080/watchlist/647a0ae83301f15c1e7fca02 HTTP/1.1
Content-Type: application/json
